### ISSUE TITLE
`yarn hardhat node` fails

### ISSUE THREAD

**Issue by ryardley** [gnosisguild/enclave#71]
Appears to fail within main as well as within `ciphernode_poc` not sure if I am missing anything here. 

```bash
cd ./packages/evm && yarn hardhat node
yarn run v1.22.22
$ /home/ry/ry/github/gnosisguild/gnosisrust/enclave/packages/evm/node_modules/.bin/hardhat node
Nothing to compile
No need to generate any newer typings.
Error HH604: Error running JSON-RPC server: ERROR processing /home/ry/ry/github/gnosisguild/gnosisrust/enclave/packages/evm/deploy/deploy.ts:
Error: invalid bytecode (argument="bytecode", value="0x6080346102a457601f612e4a38819003918201601f19168301916001600160401b038311848410176102a9578084926060946040528339810103126102a45780516001600160a01b0381168082036102a45760208301516001600160a01b03811693908490036102a45760409081015160008051602....
60a01b0316801561293a576001600160a01b037f9016d09d72d40fdae2fd8ceac6b6234c7706214fd39c1cd1e609a0528c19930054826001600160a01b03198216177f9016d09d72d40fdae2fd8ceac6b6234c7706214fd39c1cd1e609a0528c19930055167f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0600080a3565b631e4fbdf760e01b600052600060045260246000fd5b6001600160a01b03906129616129db565b16801515806129c6575b156129b2576020817f80052b810d39120cf6c976cca504a21703f585521dc7a41c6d241090e6c579b6926001600160a01b03196000541617600055604051908152a1600190565b6375ac4eb760e11b60005260045260246000fd5b506001600160a01b036000541681141561296b565b6001600160a01b037f9016d09d72d40fdae2fd8ceac6b6234c7706214fd39c1cd1e609a0528c19930054163303612a0e57565b63118cdaa760e01b6000523360045260246000fd5b60ff7ff0c57e16840df040f15088dc2f81fe391c3923bec73e23a9662efc9c229c6a005460401c1615612a5257565b631afcd79f60e31b60005260046000fdfea164736f6c634300081b000a9016d09d72d40fdae2fd8ceac6b6234c7706214fd39c1cd1e609a0528c199300f0c57e16840df040f15088dc2f81fe391c3923bec73e23a9662efc9c229c6a00", code=INVALID_ARGUMENT, version=contracts/5.7.0)
    at Logger.makeError (/home/ry/ry/github/gnosisguild/gnosisrust/enclave/packages/evm/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/home/ry/ry/github/gnosisguild/gnosisrust/enclave/packages/evm/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at Logger.throwArgumentError (/home/ry/ry/github/gnosisguild/gnosisrust/enclave/packages/evm/node_modules/@ethersproject/logger/src.ts/index.ts:285:21)
    at new ContractFactory (/home/ry/ry/github/gnosisguild/gnosisrust/enclave/packages/evm/node_modules/@ethersproject/contracts/src.ts/index.ts:1172:20)
    at new DeploymentFactory (/home/ry/ry/github/gnosisguild/gnosisrust/enclave/packages/evm/node_modules/hardhat-deploy/src/DeploymentFactory.ts:40:22)
    at fetchIfDifferent (/home/ry/ry/github/gnosisguild/gnosisrust/enclave/packages/evm/node_modules/hardhat-deploy/src/helpers.ts:836:21)
    at async _deployOne (/home/ry/ry/github/gnosisguild/gnosisrust/enclave/packages/evm/node_modules/hardhat-deploy/src/helpers.ts:913:24)
    at async Object.func (/home/ry/ry/github/gnosisguild/gnosisrust/enclave/packages/evm/deploy/deploy.ts:13:19)
    at async DeploymentsManager.executeDeployScripts (/home/ry/ry/github/gnosisguild/gnosisrust/enclave/packages/evm/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1212:22)
    at async DeploymentsManager.runDeploy (/home/ry/ry/github/gnosisguild/gnosisrust/enclave/packages/evm/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1061:5)

For more info go to https://hardhat.org/HH604 or run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

There is a possibility this is a solc version bug which is tough to figure out on nixos as I may have to compile solc from scratch or setup a docker dev container if this is the case.

**Comment by ryardley** [comment]
I setup a docker container with the latest solc and have had the same output.
